#!/usr/bin/env python3

import jojo
import sys

if __name__ == '__main__':
    if len(sys.argv) == 1:
        print ("welcome to jojo's programming adventure in python ^-^/")
        jojo.repl()
    else:
        path = sys.argv[1]
        module = jojo.load(path)
